### ISSUE TITLE
Logar requests à cielo

### ISSUE THREAD

**Issue by Sanmoo** [crafters/cielo#27]
Bom dia.

Gostaria de saber se existe alguma forma de capturar e logar as requests que a gem faz à cielo.

Grato.

**Comment by pablobender** [comment]
Olá @Sanmoo 
"Out of the box" não... mas tudo passa pela Clielo::Connection, especificamente pelo método #request!
Cuidado pra não logar dados sensíveis ;-)
Pull Requests também são bem vindos.
[]'s

**Comment by Sanmoo** [comment]
@pablobender , obrigado.

Encontrei a gem http_logger, e está resolvendo meu problema =)
