### ISSUE TITLE
Tem como colocar para capturar automaticamente?

### ISSUE THREAD

**Issue by fabiancarlos** [crafters/cielo#29]
Opa, tem como adicionar o parâmetro de capturar automaticamente??

**Comment by guialbuk** [comment]
Vendo pelo código, a gem captura automaticamente por padrão.

De qualquer modo, nos parâmetros da transação você pode colocar: ```capturar: 'true'```
````
lib/cielo/transaction.rb 

115	      xml.autorizar parameters[:autorizar].to_s
116	      xml.capturar parameters[:capturar].to_s
117	      xml.tag!("gerar-token", parameters[:"gerar-token"])
…	
141	      parameters.merge!(:autorizar => "2") unless parameters[:autorizar]
142	      parameters.merge!(:capturar => "true") unless parameters[:capturar]
````

**Comment by fabiancarlos** [comment]
Sim, percebi pelo código, mas na hora da ação, aparentemente não captura automaticamente, agora não sei exatamente se é problema no cartão do cliente ou não.

**Comment by fabiancarlos** [comment]
Conhece alguma forma de debuggar a transação pra cielo? de ver quais parâmetros ou estrutura esta sendo enviada?

**Comment by guialbuk** [comment]
Nosso colega conseguiu isso usando a gem http_logger:
https://github.com/crafters/cielo/issues/27
